ALTER TABLE IF EXISTS "project" DROP CONSTRAINT IF EXISTS "project_owner_key";
ALTER TABLE IF EXISTS "project" DROP CONSTRAINT IF EXISTS "project_owner_fkey";
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS users;