// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	AddProject(ctx context.Context, arg AddProjectParams) (string, error)
	AddUser(ctx context.Context, arg AddUserParams) (AddUserRow, error)
	GetAllProject(ctx context.Context) ([]Project, error)
	GetProject(ctx context.Context, projectName string) (Project, error)
}

var _ Querier = (*Queries)(nil)
