// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: twitter_bind_account.sql

package db

import (
	"context"
)

const createTwitterAccount = `-- name: CreateTwitterAccount :one
INSERT INTO twitter_bind_account (
    project_name,
    access_token,
    access_token_secret
) VALUES ($1, $2, $3) RETURNING id, project_name, access_token, access_token_secret
`

type CreateTwitterAccountParams struct {
	ProjectName       string `json:"project_name"`
	AccessToken       string `json:"access_token"`
	AccessTokenSecret string `json:"access_token_secret"`
}

func (q *Queries) CreateTwitterAccount(ctx context.Context, arg CreateTwitterAccountParams) (TwitterBindAccount, error) {
	row := q.queryRow(ctx, q.createTwitterAccountStmt, createTwitterAccount, arg.ProjectName, arg.AccessToken, arg.AccessTokenSecret)
	var i TwitterBindAccount
	err := row.Scan(
		&i.ID,
		&i.ProjectName,
		&i.AccessToken,
		&i.AccessTokenSecret,
	)
	return i, err
}
