// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: users.sql

package db

import (
	"context"
	"time"
)

const addUser = `-- name: AddUser :one
INSERT INTO users (
    username,
    hashed_pwd,
    user_email,
    pwd_changed_at,
    created_at
    ) VALUES ($1, $2, $3, $4, $5) RETURNING username, user_email
`

type AddUserParams struct {
	Username     string    `json:"username"`
	HashedPwd    string    `json:"hashed_pwd"`
	UserEmail    string    `json:"user_email"`
	PwdChangedAt time.Time `json:"pwd_changed_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type AddUserRow struct {
	Username  string `json:"username"`
	UserEmail string `json:"user_email"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (AddUserRow, error) {
	row := q.queryRow(ctx, q.addUserStmt, addUser,
		arg.Username,
		arg.HashedPwd,
		arg.UserEmail,
		arg.PwdChangedAt,
		arg.CreatedAt,
	)
	var i AddUserRow
	err := row.Scan(&i.Username, &i.UserEmail)
	return i, err
}
